services:
  - type: web
    name: dr-bumpy-ai
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
